### ISSUE TITLE
Add instructions on how to run rustfmt as a pre-commit hook

### ISSUE THREAD

**Issue by jdahlin** [SerenityOS/jakt#182]
This seems to be a common issue in PRs and it would be helpful.

For instance, using [pre-commit](https://pre-commit.com/):

`$ pip install pre-commit`

Adding this to `.pre-commit-config.yaml`
```yaml
-   repo: https://github.com/doublify/pre-commit-rust
    rev: master
    hooks:
    -   id: fmt
```

It also makes it trivial to add cargo-check and clippy.

Thoughts? I can create a PR with the hook config and README.md updates if needed.
